"""Disclosure notices rendered next to generated output.

Defined once so the wording cannot drift between demos.

The speech notice is not optional. Microsoft's text to speech transparency note
states that customers are required to disclose the synthetic nature of text to
speech voices to their users, and a demo in front of an audience is exactly the
setting that requirement exists for. Render it wherever synthesized audio is
played, including the offline fallback, which is also synthetic.

The generative notice covers surfaces that emit unverified model output. It is
deliberately absent from the Thinking demo's validation panel, which states that
its numbers are recomputed in code and flags unverified prose on its own. A
generic disclaimer there would make the UI less accurate, not more.
"""

from __future__ import annotations

import streamlit as st

SYNTHETIC_VOICE = "Synthetic voice. This audio is generated by a text to speech model."

AI_GENERATED = "AI-generated content, and it may be incorrect."

AUDIO_CONSENT = (
    "Upload only audio you have permission to process. A recording of a person is "
    "personal data, and consent requirements vary by jurisdiction."
)

IMAGE_PROMPT_CAUTION = (
    "Avoid prompts that target a real person or reproduce a trademarked or "
    "otherwise protected style."
)


def synthetic_voice() -> None:
    st.caption(SYNTHETIC_VOICE)


def ai_generated() -> None:
    st.caption(AI_GENERATED)


def audio_consent() -> None:
    st.caption(AUDIO_CONSENT)


def image_prompt_caution() -> None:
    st.caption(IMAGE_PROMPT_CAUTION)
